# Spring Application Configuration
spring.application.name=DevTrack

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=AvBrlmiZ3JXuicMhtYIWq5d7R9O2Rk9shAgIRd6520Cyu1MuB2
jwt.expiration=86400000

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.com.devtrack=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
